// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2kSgItYYl0N183EjjtzN_DTTaSfdJCY',
    appId: '1:868015184194:android:c5b28816d0d87bc8b990db',
    messagingSenderId: '868015184194',
    projectId: 'nola-875fe',
    databaseURL: 'https://nola-875fe-default-rtdb.firebaseio.com',
    storageBucket: 'nola-875fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuDTp5DFWow8A6U-8EYqGTxhXKMi57CA',
    appId: '1:868015184194:ios:1f1adfab0f38e28eb990db',
    messagingSenderId: '868015184194',
    projectId: 'nola-875fe',
    databaseURL: 'https://nola-875fe-default-rtdb.firebaseio.com',
    storageBucket: 'nola-875fe.firebasestorage.app',
    androidClientId: '868015184194-egnljrkucvmveckb9l4idv56n39fqs65.apps.googleusercontent.com',
    iosClientId: '868015184194-emomv617k4m6dttat757p05c75m0l5vr.apps.googleusercontent.com',
    iosBundleId: 'com.nurrtech.quarry',
  );

}